version: '3.4'

services:
  nextjs: # name of the first service
    build: ./app # specify the directory of the Dockerfile
    ports:
      - '3000:3000' # maps port 4200 on localhost to 80 in container
    depends_on:
      - 'express'

  express: # name of the second service
    build: # specify the directory of the Dockerfile
      context: ./server
      dockerfile: Dockerfile
    command: sh start.sh
    ports:
      - '8000:8000' # maps port 8000 on localhost to 8000 in container
    expose:
      - '8000'
